# PHP CircleCI 2.0 configuration file
#
version: 2
jobs:
  code-lint:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.3
    steps:
      - checkout
      - run: 
          name: Composer-normalize
          no_output_timeout: 20m
          command: composer normalize --dry-run
      - run: 
          name: PHP-Lint
          no_output_timeout: 20m
          command: parallel-lint --exclude vendor .
      - run: 
          name: Var-Dump-Check
          no_output_timeout: 20m
          command: var-dump-check .
      - run: 
          name: Merge-Conflict-Checker
          no_output_timeout: 20m
          command: merge_conflict_checker .
      - run:
          name: Magic-Number-Detector
          no_output_timeout: 20m
          command: cd ./src && phpmnd .
      - run:
          name: Copy-Paste-Checker
          no_output_timeout: 20m
          command: cd ./src && phpcpd --exclude=vendor .
  code-check:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    steps:
      - checkout
      - run:
          name: Dead-Code-Checker
          no_output_timeout: 20m
          command: cd ./src && phpdcd -vvv --exclude vendor --exclude tests .
      - run:
          name: PHP-Code-Sniffer
          no_output_timeout: 20m
          command: phpcs --ignore=./vendor/,*/tests/*,*/data/* .
  install-check:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.4
    steps:
      - checkout 
      - run: 
          name: Install-Check
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
  test:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.3
    steps:
      - checkout
      - run:
          name: Install
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit --coverage-clover=coverage.xml
      - run:
          name: CodeCov
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_create:
    jobs:
      - code-lint
      - code-check
      - install-check
      - test:
          requires:
            - code-lint
            - code-check
            - install-check
