# PHP CircleCI 2.0 configuration file
#
version: 2
jobs:
  wospm-checker:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.2
    steps:
      - checkout
      - run: 
          name: WOSPM-Checker
          no_output_timeout: 20m
          command: mkdir /tmp/tool && cd /tmp/tool && composer require --dev wospm/checker && cd - && /tmp/tool/wospm-checker
  doc-lint:
    docker:
      - image: circleci/node:9.8
    steps:
      - checkout
      - run:
          name: Project-Markdown-Lint
          no_output_timeout: 20m
          command: sudo npm install -g markdownlint-cli && markdownlint *.md CODE_OF_CONDUCT
      - run:
          name: Metrics-Markdown-Lint
          no_output_timeout: 20m
          command: sudo npm install -g markdownlint-cli && markdownlint mdocs/*.md
  code-lint:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    steps:
      - checkout
      - run: 
          name: Composer-normalize
          no_output_timeout: 20m
          command: composer normalize --dry-run
      - run: 
          name: PHP-Lint
          no_output_timeout: 20m
          command: parallel-lint --exclude vendor .
      - run: 
          name: Var-Dump-Check
          no_output_timeout: 20m
          command: var-dump-check .
      - run: 
          name: Merge-Conflict-Checker
          no_output_timeout: 20m
          command: merge_conflict_checker .
      - run:
          name: Magic-Number-Detector
          no_output_timeout: 20m
          command: cd ./src && phpmnd .
      - run:
          name: Dead-Code-Checker
          no_output_timeout: 20m
          command: cd ./src && phpdcd -vvv --exclude vendor --exclude tests .
      - run:
          name: Copy-Paste-Checker
          no_output_timeout: 20m
          command: cd ./src && phpcpd --exclude=vendor .
      - run:
          name: PHP-Code-Sniffer
          no_output_timeout: 20m
          command: phpcs --ignore=./vendor/,*/tests/*,*/data/* .
  install-check:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    steps:
      - checkout 
      - run: 
          name: Install-Check
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
  test-5.6:
    docker:
        - image: umutphp/php-docker-images-for-ci:5.6
    steps:
      - checkout
      - run: 
          name: Install-5-6
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.0:
    docker:
        - image: umutphp/php-docker-images-for-ci:7.0
    steps:
      - checkout
      - run:
          name: Install-7-0
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.1:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    steps:
      - checkout
      - run:
          name: Install-7-1
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.2:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.2
    steps:
      - checkout
      - run:
          name: Install-7-2
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.3:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.3
    steps:
      - checkout
      - run:
          name: Install-7-3
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit --coverage-clover=coverage.xml
      - run:
          name: CodeCov
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build_and_create:
    jobs:
      - wospm-checker
      - doc-lint:
          requires:
            - wospm-checker
      - code-lint:
          requires:
            - wospm-checker
      - test-5.6:
          requires:
            - doc-lint
            - code-lint
      - test-7.0:
          requires:
            - doc-lint
            - code-lint
      - test-7.1:
          requires:
            - doc-lint
            - code-lint
      - test-7.2:
          requires:
            - doc-lint
            - code-lint
      - test-7.3:
          requires:
            - doc-lint
            - code-lint
