# PHP CircleCI 2.0 configuration file
#
version: 2
jobs:
  wospm-checker:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.3
    steps:
      - checkout
      - run: 
          name: WOSPM-Checker
          no_output_timeout: 20m
          command: mkdir /tmp/tool && cd /tmp/tool && composer require --dev wospm/checker && cd - && /tmp/tool/wospm-checker
  code-lint:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.3
    steps:
      - checkout
      - run: 
          name: Composer-normalize
          no_output_timeout: 20m
          command: composer normalize --dry-run
      - run: 
          name: PHP-Lint
          no_output_timeout: 20m
          command: parallel-lint --exclude vendor .
      - run: 
          name: Var-Dump-Check
          no_output_timeout: 20m
          command: var-dump-check .
      - run: 
          name: Merge-Conflict-Checker
          no_output_timeout: 20m
          command: merge_conflict_checker .
      - run:
          name: Magic-Number-Detector
          no_output_timeout: 20m
          command: cd ./src && phpmnd .
      - run:
          name: Copy-Paste-Checker
          no_output_timeout: 20m
          command: cd ./src && phpcpd --exclude=vendor .
  code-check:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    steps:
      - checkout
      - run:
          name: Dead-Code-Checker
          no_output_timeout: 20m
          command: cd ./src && phpdcd -vvv --exclude vendor --exclude tests .
      - run:
          name: PHP-Code-Sniffer
          no_output_timeout: 20m
          command: phpcs --ignore=./vendor/,*/tests/*,*/data/* .
  install-check:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.3
    steps:
      - checkout 
      - run: 
          name: Install-Check
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
  test-7.1:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.1
    steps:
      - checkout
      - run:
          name: Install-7-1
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.2:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.2
    steps:
      - checkout
      - run:
          name: Install-7-2
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
  test-7.3:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.3
    steps:
      - checkout
      - run:
          name: Install-7-3
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit --coverage-clover=coverage.xml
      - run:
          name: CodeCov
          command: bash <(curl -s https://codecov.io/bash)
  test-7.4:
    docker:
      - image: umutphp/php-docker-images-for-ci:7.4
    steps:
      - checkout
      - run:
          name: Install-7-4
          no_output_timeout: 20m
          command: composer install --no-interaction --prefer-source
      - run:
          name: Unittest
          command: ./phpunit
workflows:
  version: 2
  build_and_create:
    jobs:
      - wospm-checker
      - code-lint:
          requires:
            - wospm-checker
      - code-check:
          requires:
            - wospm-checker
      - test-7.1:
          requires:
            - code-lint
            - code-check
      - test-7.2:
          requires:
            - code-lint
            - code-check
      - test-7.3:
          requires:
            - code-lint
            - code-check
      - test-7.4:
          requires:
            - code-lint
            - code-check
