on: [push]

jobs:
  wospm_checker:
    runs-on: ubuntu-latest
    name: WOSPM Checker
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: WOSPM Checker action step
        uses: actions/wospm-checker-github-action@v1
      - name: Upload HTML Report When Success
        uses: actions/upload-artifact@v1
        with:
          name: HTML Report
          path: wospm.html
      - name: Upload HTML Report When Failed
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: HTML Report
          path: wospm.html